### ISSUE TITLE
Missing access error when audit logging system is given an inaccessible channel.

### ISSUE THREAD

**Issue by AndyNoob** [Insprill/robot-insprill#9]
# Problem
When implementing forms, this particular error was thrown when the audit system detects something to log and the channel specified in config does not exist/is not accessible:

## Error
```stacktrace
[15:02:16 ERROR]: catching
dev.kord.rest.request.KtorRequestException: REST request returned an error: 403 Forbidden  Missing Access null
	at dev.kord.rest.request.KtorRequestHandler.handle(KtorRequestHandler.kt:61)
	at dev.kord.rest.request.KtorRequestHandler$handle$1.invokeSuspend(KtorRequestHandler.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: dev.kord.rest.request.RecoveredStackTrace: This is the recovered stack trace:
		at dev.kord.rest.service.ChannelService.getChannel(ChannelService.kt:525)
		at dev.kord.core.supplier.RestEntitySupplier.getChannelOrNull(RestEntitySupplier.kt:86)
		at dev.kord.core.supplier.StoreEntitySupplier.getChannelOrNull(StoreEntitySupplier.kt:50)
		at dev.kord.core.supplier.FallbackEntitySupplier.getChannelOrNull(FallbackEntitySupplier.kt:38)
		at dev.kord.core.behavior.GuildBehavior$DefaultImpls.getChannel(GuildBehavior.kt:1109)
		at dev.kord.core.entity.Guild.getChannel(Guild.kt:34)
		at net.insprill.robotinsprill.audit.AuditManager.sendMessage(AuditManager.kt:49)
		at net.insprill.robotinsprill.audit.AuditManager.sendUserMessage(AuditManager.kt:34)
		at net.insprill.robotinsprill.audit.category.AuditCategory.send(AuditCategory.kt:19)
		at net.insprill.robotinsprill.audit.category.AuditMessages$registerEvents$2.invokeSuspend(AuditMessages.kt:32)
		at net.insprill.robotinsprill.audit.category.AuditMessages$registerEvents$2.invoke(AuditMessages.kt)
		at net.insprill.robotinsprill.audit.category.AuditMessages$registerEvents$2.invoke(AuditMessages.kt)
		at net.insprill.robotinsprill.audit.category.AuditMessages$registerEvents$$inlined$event$4$1.invokeSuspend(Kord.kt:636)
		... 6 common frames omitted
```

## Why
This error occurs because `AuditManager#sendMessage` invokes `#getChannel`, which throws an error if the specified channel could not be retrieved.

## Alternative
Use `#getChannelOrNull` and boxing it with try/catch.

**Comment by Insprill** [comment]
No Discord-related config options are currently validated - its assumed the user double-checked that everything is entered correctly and the bot has the proper permissions on the Discord side. Perhaps its something that can be improved upon in the future, but for now it's a pretty low priority.
